import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
class RivalEncountersTest {
 private GameSession ready(){Player p=new Warrior("A");p.setLevel(10);p.setHealth(70);p.setResource(25);p.setCoins(100);GameSave s=new GameSession(p,new Random(1)).snapshot();return GameSession.restore(new GameSave(1,s.player(),"TOWN",s.area(),0,3,0,0,0,Set.of(),Set.of(SubArea.get(1).key()),s.inventory(),s.equipped(),s.log(),null),new Random(1));}
 private GameSession battle(GameSession g,int hp,int enemyHp,int attack){GameSave s=g.snapshot();var p=s.player();var e=s.battle();return GameSession.restore(new GameSave(1,new GameSave.PlayerData(p.name(),p.type(),p.level(),p.xp(),hp,p.resource(),p.coins(),p.potions(),p.swordDamage()),s.mode(),s.area(),s.room(),s.kills(),s.deaths(),s.towerBest(),s.towerFloor(),s.cleared(),s.claimed(),s.inventory(),s.equipped(),s.log(),new GameSave.BattleData(e.name(),e.level(),e.maxHealth(),enemyHp,attack,e.defence(),e.boss(),0,e.cooldowns(),List.of(),List.of())),new Random(1));}
 @Test void resumedWinPaysOnceWithoutLootOrCampaignProgress(){GameSession g=ready();GameSave before=g.snapshot();g.command("rival","0");g=battle(g,70,1,1);g.command("combat","ATTACK");GameSave after=g.snapshot();assertEquals("TOWN",after.mode());assertEquals(before.player().xp(),after.player().xp());assertEquals(120,after.player().coins());assertEquals(70,after.player().health());assertEquals(25,after.player().resource());assertEquals(before.player().potions(),after.player().potions());assertEquals(before.kills(),after.kills());assertEquals(before.inventory(),after.inventory());assertEquals(before.cleared(),after.cleared());GameSession won=g;assertThrows(IllegalArgumentException.class,()->won.command("rival","0"));}
 @Test void lossRestoresSuppliesAndNeverPenalises(){GameSession g=ready();GameSave before=g.snapshot();g.command("rival","0");g=battle(g,1,100,10000);g.command("combat","ATTACK");assertEquals(before.player(),g.snapshot().player());assertEquals(before.deaths(),g.snapshot().deaths());assertEquals("TOWN",g.snapshot().mode());assertFalse(g.snapshot().claimed().contains(RivalEncounters.key(0)));g.command("rival","0");assertEquals("COMBAT",g.snapshot().mode());}
 @Test void laterBoutsRequireStoryAndEarlierVictory(){GameSession g=ready();assertThrows(IllegalArgumentException.class,()->g.command("rival","1"));GameSession fresh=new GameSession(new Mage("A"),new Random(1));assertThrows(IllegalArgumentException.class,()->fresh.command("rival","0"));}
}
