import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import java.security.Principal;
import java.util.*;

@RestController
@RequestMapping("/api/social")
public class SocialController {
    private final SocialStore store;private final TransactionTemplate tx;
    private static final java.security.SecureRandom RANDOM=new java.security.SecureRandom();
    private final Map<String,long[]> limits=new HashMap<>();
    public SocialController(SocialStore store,PlatformTransactionManager manager){this.store=store;tx=new TransactionTemplate(manager);}
    public record Command(long version,String action,String value,Long generation) {public Command {if(generation==null)generation=0L;}}
    private String code(){String chars="ABCDEFGHJKMNPQRSTUVWXYZ23456789";StringBuilder b=new StringBuilder();for(int n=0;n<8;n++)b.append(chars.charAt(RANDOM.nextInt(chars.length())));return b.toString();}
    private synchronized void limit(String user){long now=System.currentTimeMillis();limits.entrySet().removeIf(e->now-e.getValue()[0]>60000);long[] w=limits.get(user);if(w==null){CoopDungeon.require(limits.size()<10000,"Try again in a minute.");w=new long[]{now,0};limits.put(user,w);}CoopDungeon.require(++w[1]<=20,"Too many social actions. Try again in a minute.");}
    @GetMapping public Map<String,Object> get(Principal principal){return view(principal.getName());}
    @PostMapping public Map<String,Object> command(Principal principal,@RequestBody Command body){String user=principal.getName();limit(user);return tx.execute(status->{SocialStore.lock(store.jdbc);String id=store.guildId(user),action=body.action()==null?"":body.action(),value=body.value()==null?"":body.value().strip();
        if(action.equals("create")){store.available(user);CoopDungeon.require(id==null,"You already belong to a guild.");CoopDungeon.require(value.matches("[\\p{L}\\p{N} _-]{3,28}"),"Use 3–28 letters, numbers, spaces or dashes.");id=UUID.randomUUID().toString().replace("-","");GuildHouse g=new GuildHouse();g.name=value;g.owner=user;g.invite=code();g.record(user+" founded the guild.");store.jdbc.update("INSERT INTO hearthglen.rpg_guild(id,payload) VALUES (?,?)",id,store.json.writeValueAsString(g));store.jdbc.update("INSERT INTO hearthglen.rpg_guild_member(username,guild_id) VALUES (?,?)",user,id);return view(user);}
        if(action.equals("join")){store.available(user);CoopDungeon.require(id==null,"Leave your current guild first.");CoopDungeon.require(value.matches("[A-Za-z2-9]{8}"),"Enter the eight-character invite.");final String invite=value.toUpperCase(Locale.ROOT);String found=store.jdbc.query("SELECT id,payload FROM hearthglen.rpg_guild",(r,n)->Map.entry(r.getString(1),store.json.readValue(r.getString(2),GuildHouse.class))).stream().filter(e->invite.equals(e.getValue().invite)).map(Map.Entry::getKey).findFirst().orElseThrow(()->new IllegalArgumentException("Invite not found."));GuildHouse g=store.guild(found);CoopDungeon.require(store.members(found).size()<2,"This guild is full (two members).");store.jdbc.update("INSERT INTO hearthglen.rpg_guild_member(username,guild_id) VALUES (?,?)",user,found);g.invite=code();g.record(user+" joined the guild.");store.saveGuild(found,g);return view(user);}
        CoopDungeon.require(id!=null,"Create or join a guild first.");GuildHouse g=store.guild(id);if(body.version()!=g.version)throw new GameRepository.StaleGameException();
        switch(action){
            case "emblem" -> {CoopDungeon.require(Set.of("leaf","moon","sun","sword").contains(value),"Choose an emblem.");g.emblem=value;}
            case "invite" -> {CoopDungeon.require(user.equals(g.owner),"Only the founder can renew the invite.");g.invite=code();}
            case "donate" -> {CharacterSlots.validate(store.jdbc,user,body.generation());store.available(user);CoopDungeon.require(Set.of("10","25","50").contains(value),"Choose a contribution amount.");int amount=Integer.parseInt(value);GameSave s=store.character(user);CoopDungeon.require(s.player().coins()>=amount,"Not enough coins.");GameSave.PlayerData p=s.player();GameSave.PlayerData paid=new GameSave.PlayerData(p.name(),p.type(),p.level(),p.xp(),p.health(),p.resource(),p.coins()-amount,p.potions(),p.swordDamage());GameSave next=new GameSave(s.schemaVersion(),paid,s.mode(),s.area(),s.room(),s.kills(),s.deaths(),s.towerBest(),s.towerFloor(),s.cleared(),s.claimed(),s.inventory(),s.equipped(),s.log(),s.battle());store.jdbc.update("UPDATE hearthglen.rpg_saves SET payload=?,version=version+1 WHERE username=?",store.json.writeValueAsString(next),user);g.coins=Math.addExact(g.coins,amount);g.record(user+" contributed "+amount+" coins.");}
            case "upgrade" -> {CoopDungeon.require(g.upgrade<3,"Your house is fully improved.");int[] coins={50,100,180},supplies={0,2,4};CoopDungeon.require(g.coins>=coins[g.upgrade]&&g.materials>=supplies[g.upgrade],"The guild needs more coins or adventure supplies.");g.coins-=coins[g.upgrade];g.materials-=supplies[g.upgrade];g.upgrade++;g.record(user+" improved the house to stage "+g.upgrade+".");}
            case "buy" -> {GuildHouse.Decoration d=GuildHouse.decoration(value);CoopDungeon.require(d.requirement().isEmpty(),"Earn this decoration through adventures together.");CoopDungeon.require(!g.owned.contains(value),"Already owned.");CoopDungeon.require(g.coins>=d.price(),"Not enough guild coins.");g.coins-=d.price();g.owned.add(value);g.record(user+" bought "+d.name()+".");}
            case "place" -> {GuildHouse.Decoration d=GuildHouse.decoration(value);CoopDungeon.require(g.owned.contains(value),"Your guild does not own this decoration.");g.placed.put(d.slot(),value);g.record(user+" placed "+d.name()+".");}
            case "react" -> {Map<String,String> messages=Map.of("cheer","Cheers to our next adventure!","thanks","Thanks for having my back.","ready","Ready when you are!","close","That was far too close.");CoopDungeon.require(messages.containsKey(value),"Choose a reaction.");long now=System.currentTimeMillis();CoopDungeon.require(now-g.reactions.getOrDefault(user,0L)>=10000,"Wait a moment before another reaction.");g.reactions.put(user,now);g.guestbook.add(user+": "+messages.get(value));while(g.guestbook.size()>20)g.guestbook.remove(0);}
            case "leave" -> {store.available(user);List<String> members=store.members(id);CoopDungeon.require(!user.equals(g.owner)||members.size()==1,"The founder can leave after the other member leaves. The house stays with this guild.");store.jdbc.update("DELETE FROM hearthglen.rpg_guild_member WHERE username=?",user);g.record(user+" left the guild.");if(members.size()==1)g.invite=null;}
            default -> throw new IllegalArgumentException("Unknown guild action.");
        }
        store.saveGuild(id,g);return view(user);
    });}
    private Map<String,Object> view(String user){String id=store.guildId(user);if(id==null)return Map.of("joined",false);GuildHouse g=store.guild(id);List<String> members=store.members(id);SocialStore.Bond bond=members.size()==2?store.bond(members.get(0),members.get(1)):new SocialStore.Bond();Map<String,Object> out=new LinkedHashMap<>();out.put("joined",true);out.put("name",g.name);out.put("emblem",g.emblem);out.put("version",g.version);out.put("owner",user.equals(g.owner));out.put("invite",user.equals(g.owner)?g.invite:"");out.put("members",members);out.put("coins",g.coins);out.put("materials",g.materials);out.put("upgrade",g.upgrade);out.put("owned",g.owned);out.put("placed",g.placed);out.put("history",g.history);out.put("guestbook",g.guestbook);out.put("catalog",GuildHouse.CATALOG);out.put("bond",bond);return out;}
}
