import java.util.*;

/** Twelve authored routes. Story clears open the next route; levels describe its threats. */
public record SubArea(int index,Area area,String name,int minLevel,int maxLevel,String captain,String mission,String opening,String ending,String guardian) {
    public String key(){return "route:clear:"+index;}
    public static final List<SubArea> ALL=List.of(
        new SubArea(0,Area.WHISPERING_WOODS,"Old Timberline",1,5,"Captain Elin Ward","Food for the frontier","Elin: ‘Walk beside the wagons. If the road falls, Hearthglen goes hungry.’ Tessa takes the lead rope. Cedric rides ahead without looking back.","The wagons reach the settlement. Tessa shares the first loaf with the watch. Elin orders a search for the missing patrol at Hollow Reach.","Timberline Packleader"),
        new SubArea(1,Area.WHISPERING_WOODS,"Hollow Reach",5,10,"Tessa Reed","The silent watch","Tessa: ‘Three signal fires should be visible here. There are none.’ You find claw marks over a watchpost door and fresh tool marks around its ward socket.","The surviving watchmen carry a broken crown seal. Cedric calls it theft; Tessa points out that thieves rarely carry royal tools. The tracks lead into Blighted Grove.","Blighted Watchhound"),
        new SubArea(2,Area.WHISPERING_WOODS,"Blighted Grove",10,15,"Captain Elin Ward","A road reclaimed","Elin: ‘Stop the pack, then bring back the seal. The court will need evidence.’ Cedric stays to cover the road this time, without being asked.","The Alpha Wolf falls beside a stripped ward. Elin recognizes your company’s service with its first promotion. The seal’s requisition number belongs to Stonefang. The miners may know who took it.","Alpha Wolf"),
        new SubArea(3,Area.STONEFANG_CAVES,"Entrance Tunnels",16,20,"Keeper Rowan Flint","Lamps below the mountain","Rowan: ‘My people are still below. Bring them out before you ask about missing stone.’ You follow abandoned lamps into the tunnels while Tessa organizes the returning families.","The last miners emerge. Rowan opens his records: ward-stone was shipped under military authority. He will guide you to the Deep Shaft to recover the original order.","Tunnel Broodmother"),
        new SubArea(4,Area.STONEFANG_CAVES,"Deep Shaft",21,25,"Keeper Rowan Flint","The sealed order","The shaft office lies beyond a monster-held lift. Rowan: ‘That signature purchased silence as well as stone.’ Cedric recognizes his house’s crest on an empty crate.","You recover the order intact. Cedric asks for one night before it reaches Elin. You refuse; he follows you anyway. The Chieftain holds the passage through The Fracture.","Shaft Overseer"),
        new SubArea(5,Area.STONEFANG_CAVES,"The Fracture",26,30,"Captain Elin Ward","Open the mountain road","Elin: ‘We investigate houses after we bring our people home. Open that passage.’ Rowan marks the Hollow Vein on your chart for a safer future, once the fighting ends.","The Orc Chieftain’s blockade breaks. Your second promotion names the miners you brought home. The requisition refers to an archive beneath the old royal quarter. Cedric insists on seeing it himself.","Orc Chieftain"),
        new SubArea(6,Area.FORGOTTEN_RUINS,"Outer Colonnade",31,35,"Tessa Reed","A way out for the living","Tessa is escorting families through the ruined quarter when the dead cut off the road. ‘Hold the colonnade. They cannot outrun what is following us.’", "The families escape along the reopened road. A keeper gives Tessa a chapel key: the Sunken Hall holds the testimony the court tried to bury.","Colonnade Sentinel"),
        new SubArea(7,Area.FORGOTTEN_RUINS,"Sunken Hall",36,40,"Cedric Ashford","The price of a name","Cedric reaches the testimony first. ‘If this is true, everything my father promised was bought with stolen wards.’ The dead close in before he can hide the pages.","Cedric carries a wounded keeper out instead of taking the evidence. He leaves the pages in your hands. ‘Let the crown hear it.’ The pact itself remains in the Drowned Archive.","Drowned Castellan"),
        new SubArea(8,Area.FORGOTTEN_RUINS,"The Drowned Archive",41,45,"Keeper Rowan Flint","What the kingdom swore","Rowan reads the pact: Cindergard guarded the boundary wards; the dragons left its settlements untouched. A royal faction dismantled those wards to build weapons. Ashwing answered with devastation. The Lich Acolyte feeds on both betrayals.","The ritual ends. Your third promotion carries an order to protect the Spire’s foothills. Neither a noble seal nor an old grievance excuses killing civilians. The company will confront Ashwing.","Lich Acolyte"),
        new SubArea(9,Area.DRAGONS_SPIRE,"Ashen Approach",46,50,"Captain Elin Ward","A foothold in the ash","Elin: ‘An army marches on what reaches its camp. Secure the approach before anyone climbs.’ Cedric takes a place among the wagon guards, his house’s crest covered.","A defended supply camp replaces the abandoned roadblock. Messages from Hearthglen arrive with fresh provisions. Your next duty is to hold the Scarred Path against the creatures descending from the summit.","Ashen Wyvern"),
        new SubArea(10,Area.DRAGONS_SPIRE,"The Scarred Path",51,55,"Cedric Ashford","For those below","An order bearing Cedric’s family seal commands him to withdraw and surrender the evidence. He tears it in half. ‘My oath was to Cindergard. Stand with me.’", "The assault breaks against your company. Cedric sends the evidence to court under his own name. Tessa carries the survivors down; you advance toward the Wyrm’s Hollow.","Stormbound Guardian"),
        new SubArea(11,Area.DRAGONS_SPIRE,"The Wyrm's Hollow",56,60,"Captain Elin Ward","The duty that remains","Ashwing waits above the broken pact sanctuary. ‘Your kingdom stole the peace.’ Elin answers: ‘Then its court will answer for it. Its children will not.’ Your company advances together.","Ashwing falls. In Cindergard’s court, the requisitions are read aloud and the responsible nobles stripped of command. Cedric testifies. Elin names your final rank and the title Dragonbane. Back in Hearthglen, Mara sets two more places at the table. The roads remain open; the kingdom’s future is work you can share.","Ashwing, the Red Wyrm")
    );
    public static SubArea get(int index){return ALL.get(index);}
    public boolean complete(Set<String> flags,Set<String> cleared){return flags.contains(key())||cleared.contains(area.name());}
    public boolean unlocked(Set<String> flags,Set<String> cleared){return complete(flags,cleared)||index==0||get(index-1).complete(flags,cleared);}
    public Enemy encounter(int room,int playerLevel,Random random){
        int level=room==4?maxLevel:Math.max(minLevel,Math.min(maxLevel,playerLevel));
        Enemy enemy=Campaign.encounter(area,level,room==4,random,0);
        if(room!=4)return enemy;
        int xp=Balance.enemyXp(level)*2;
        return new Enemy(guardian,level,enemy.getMaxHealth(),enemy.getAttackPower(),enemy.getDefence(),4+level,8+level*2,xp,xp).asBoss();
    }
}
